const USER_ACTION_TYPE = {
  FETCH_USERS: "FETCH_USERS",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  FETCH_USER_FAIL: "FETCH_USER_FAIL",
  POST_USERS: "POST_USERS",
  POST_USERS_SUCCESS: "POST_USERS_SUCCESS",
  POST_USER_FAIL: "POST_USER_FAIL",
};

export default USER_ACTION_TYPE;
